input: training_files.txt
output: output
graph: utils/pmt_graph.pt
stats: utils/norm_stats.npz

training:
  epochs: 100
  batch_size: 10
  lr: 0.001
  latent_dim: 32
  hidden_dim: 64
  patience: 10
  limit: 10
  num_workers: 4
  loss: regression
  target: energy