input: evaluation_files_nu_mu.txt
output: output
graph: utils/pmt_graph.pt
stats: utils/norm_stats.npz
sh: utils/spherical_harmonics.npz

training:
  epochs: 100
  batch_size: 16
  lr: 0.001
  latent_dim: 64
  hidden_dim: 64
  patience: 10
  limit: 
  num_workers: 6
  loss: regression
  class_type: 
  target: energy