input: training_files_nu_e.txt
output: output
graph: utils/pmt_graph.pt
stats: utils/norm_stats.npz

training:
  epochs: 100
  batch_size: 32
  lr: 0.001
  latent_dim: 64
  hidden_dim: 128
  patience: 10
  limit: 
  num_workers: 6
  loss: regression
  class_type: 
  target: energy